---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reader
  namespace: k8squest
---
# ❌ Missing Role! ServiceAccount has no permissions
# ❌ Missing RoleBinding! ServiceAccount not bound to any Role
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-lister
  namespace: k8squest
spec:
  serviceAccountName: pod-reader  # Uses ServiceAccount, but it has no permissions
  containers:
  - name: app
    image: bitnami/kubectl:latest
    command:
    - sh
    - -c
    - |
      echo "Attempting to list pods..."
      kubectl get pods -n k8squest
      
      if [ $? -eq 0 ]; then
        echo "✅ Success! Can list pods"
        sleep 3600
      else
        echo "❌ ERROR: Permission denied - cannot list pods"
        echo "Check RBAC configuration!"
        exit 1
      fi
